### PR TITLE
Add throttle option for v-model

### LINKED ISSUE #52: Improve performance when editing large content in ckeditor4-vue
I noticed that when editing large content in ckeditor4 could be very slow, and I already seen that issue has been fixed in https://github.com/ckeditor/ckeditor5-vue/pull/46, so is there a way to do the same fix in ckeditor4 please？

### PR DESCRIPTION
**Pull request by jacekbogdanski**
It seems like simple throttling should do the job. Note that we can't use `CKEDITOR.tools.throttle/eventsBuffer` here because these methods are calling function after X time every time and we need a function to debounce output by X ms once.

Changelog entry under `New features`:

```
* [#52](https://github.com/ckeditor/ckeditor4-vue/issues/52) Improved typing performance by adding [customizable throttling option](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#throttle).
```

Closes #52

### CODE REVIEW

**Comment by f1ames** [comment]
@jacekbogdanski I guess this PR will be updated to use common `debounce` function (ckeditor/ckeditor4-integrations-common#6) as you mentioned?

**Comment by jacekbogdanski** [comment]
That's right. I will take care of it soon.

**Comment by jacekbogdanski** [comment]
PR is ready for review.

**Review by Dumluregn — CHANGES_REQUESTED** [review]
Everything works fine 👍 

Only one request from me - please add a test checking if the custom `throttle` value passed through the config correctly changes the debounce time (I know there is already a test checking if it is correctly assigned to the component but still will be useful to check if it is used as expected).

**Review by Dumluregn — APPROVED** [review]
LGTM! 🎉 🌮

**Pull request merged**
