### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sculpt0r**

### CODE REVIEW

**Comment by jacekbogdanski** [comment]
From what I see there are a bit more deps we can update right now. We can also follow here the same approach as in CKE4 repo, so to remove `package-lock.json` file following the same decision factor:
```
# Ignore package-lock.json
# - we don't intent to force specific 3rd party dependency version via `package-lock.json` file
# Such information should be specified in the package.json file.
package-lock.json
```

There are 3 deps that are really resistant for updating:
* karma-webpack
* terser-webpack-plugin
* webpack

I'm getting similar conflict information when trying to update them:
image

I'm not sure why it happens so it's worth investigating. Also, we are getting some errors about using deprecated API in our tests that is also worth checking (or extracting): 
image

**Comment by jacekbogdanski** [comment]
I've rerun the build, it was failing via our usual Safari timeout.

**Review by jacekbogdanski — CHANGES_REQUESTED** [review]
@sculpt0r could you take a look at whether we will be able to update these karma-related deps and what's going with info about test utils deprecation?

**Comment by sculpt0r** [comment]
Utils were bumped barely above the beta version during the last refactor /  feature introduction (detach editor support). We were able to improve them a little, but AFAIR - the main construction of tests still uses the deprecated option. Probably sth that could be improved. However, that might require some tests refactor.

As for webpack and karma I'll take a look :)

**Comment by sculpt0r** [comment]
@jacekbogdanski - ready for another review. I've made a few approaches (you can see them in commits) to upgrade deps to the newest ones - but it all fails. I decided to not spend more time on it... Probably next try will be while supporting Vue3 will be processed.
- we can't bump sinon no more: https://github.com/sinonjs/sinon/blob/main/CHANGES.md#1000 They drop IE 11 support at version `10`
- I managed to bump webpack to version 5, also with replacing `istanbul-instrumenter-loader` on `babel-plugin-istanbul`. That solution works for the builder version, but there were issues with running tests... Webpack5 works well with the newest sinon, but the newest sinon doesn't work on IE 11 - on tests... As tried - mainly due to used backticks. I tried to transpile it somehow - but without luck... Then I tried webpack5 with old sinon, which is also troublesome - so I tried to add some initial utils older, but that leads me to another error on tests: `undefined process`...
- Due to all above, I decide to downgrade webpack again... but webpack4 doesn't work with `babel-plugin-istanbul`, so I also switch back on Istanbul...

I didn't touch tests deprecation methods - since it probably requires rewriting all tests...

**Review by jacekbogdanski — APPROVED** [review]

**Pull request merged**
