### PR TITLE
"Permission" denied in IE11.

### LINKED ISSUE #121: "Permission denied" in IE11
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

just a simple usage of the editor already gives the error, just check the repo "https://github.com/whity/ckeditor4-vue-ie11"

### Expected result

error should not appear

### Actual result

error is always present

## Other details

* Browser: IE11
* OS: win81 (virtualbox)
* Integration version: 1.3.2
* CKEditor version: 4.16.2
* Installed CKEditor plugins: 

  ```
        codemirror: 1,
        a11yhelp: 1,
        about: 1,
        basicstyles: 1,
        bidi: 1,
        blockquote: 1,
        clipboard: 1,
        colorbutton: 1,
        colordialog: 1,
        copyformatting: 1,
        contextmenu: 1,
        dialogadvtab: 1,
        div: 1,
        editorplaceholder: 1,
        // elementspath: 1,
        enterkey: 1,
        entities: 1,
        exportpdf: 1,
        filebrowser: 1,
        find: 1,
        flash: 1,
        floatingspace: 1,
        font: 1,
        format: 1,
        forms: 1,
        horizontalrule: 1,
        htmlwriter: 1,
        iframe: 1,
        // image: 1,
        indentblock: 1,
        indentlist: 1,
        justify: 1,
        language: 1,
        link: 1,
        list: 1,
        liststyle: 1,
        magicline: 1,
        maximize: 1,
        newpage: 1,
        pagebreak: 1,
        pastefromgdocs: 1,
        pastefromlibreoffice: 1,
        pastefromword: 1,
        pastetext: 1,
        preview: 1,
        print: 1,
        removeformat: 1,
        resize: 1,
        save: 1,
        scayt: 1,
        selectall: 1,
        showblocks: 1,
        showborders: 1,
        smiley: 1,
        sourcearea: 1,
        specialchar: 1,
        stylescombo: 1,
        tab: 1,
        table: 1,
        tableselection: 1,
        tabletools: 1,
        templates: 1,
        toolbar: 1,
        undo: 1,
        uploadimage: 1,
        wysiwygarea: 1,
        image2: 1,
        wsc: 1,
```

### PR DESCRIPTION
**Pull request by whity**
Hello,

I was also getting the problem of "Permission denied" in IE11, this change fixed the issue.
It seems at the time of the event "instanceReady" the element isn't ready yet at the DOM.

Thank you.

Best regards

[EDITED]

Closes #121

### CODE REVIEW

**Review by sculpt0r — CHANGES_REQUESTED** [review]
Hi @whity 
Thank you for your commitment to CKE4 development. Your change seems to be correct - all of our tests passed.

However, could you elaborate on the issue you are experiencing? Best if you create an issue with a description of all problems. In that way, we will be able to verify such issue and your PR may close it.

Just to be clear: we want to be 100% sure, that the code we will merge is solving a valid issue. That is pretty much the standard way because we have time to verify if the reported bug is actually a valid report for us. And then - if the problem is confirmed - we can fix it.

So, I'm not closing this PR, however, please create a new issue for the problem with permission denied message (frequency of occurrence, environment, dependencies etc.). Then if it will be possible, please add some tests to the PR. Then we will be back to the review.

**Comment by whity** [comment]
Hey @sculpt0r 

Thanks for the feedback, I'll try to find some time do it :).

**Comment by sculpt0r** [comment]
Thank you @whity,
I will take a look at that soon. I had a few days OFF recently.

**Review by sculpt0r — APPROVED** [review]
Thank you for the commitment! 👍  🙇 

I'm so sorry for the long delay, but the pre-released time was so engaging.

Thank you for the fix :)

**Pull request merged**
