### PR TITLE
Add IE11 BrowserStack custom launcher.

### LINKED ISSUE #9: Enable IE11 testing environment
IE11 testing via BrowserStack should be enabled similarly like it has been done for [Angular](https://github.com/ckeditor/ckeditor4-angular/blob/6e19e8e33b36ead3f1ee8e199e4ab2a31f58c165/src/karma.conf.js#L51) integration.

### LINKED ISSUE #75: IE 11 Compatibility
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Plugin version 1.2.0
2. Use with command: import CKEditor from 'ckeditor4-vue/dist/legacy.js'
3. Check in IE 11

### Expected result

Proper work of editor

### Actual result

Syntax error in build.
Error leads me to webpack://ckeditor/node_modules/ckeditor4-integrations-common/src/getEditorNamespace.js:47

## Other details

With version 1.1.0 it works fine

### PR DESCRIPTION
**Pull request by sculpt0r**
Add IE11 BrowserStack custom launcher

Closes #9

Closes #75

### CODE REVIEW

**Comment by sculpt0r** [comment]
Blocked by: #75

**Comment by sculpt0r** [comment]
Seems that CI is green. However, locally few tests are down. I talked with @jacekbogdanski and he points me to ckeditor/ckeditor4-angular#119. However running single `Chrome` / `Firefox` stills fail on  
\`\`\`  
SUMMARY:  
✔ 43 tests completed  
✖ 3 tests failed

FAILED TESTS:  
 CKEditor Component  
   when "component.value" changes to "foo"  
     ✖ should call "instance.setData"  
       Chrome 87.0.4280.66 (Linux x86\_64)  
     AssertError: expected setData to be called with arguments   
         at Object.fail (tests/component.js:30493:25)  
         at failAssertion (tests/component.js:30450:20)  
         at Object.assert.\<computed> \[as calledWith\] (tests/component.js:30476:17)  
         at Context.\<anonymous> (tests/component.js:51840:63)

   when "component.readOnly" changes to "true"  
     ✖ should call "instance.setReadOnly"  
       Chrome 87.0.4280.66 (Linux x86\_64)  
     AssertError: expected setReadOnly to be called with arguments   
         at Object.fail (tests/component.js:30493:25)  
         at failAssertion (tests/component.js:30450:20)  
         at Object.assert.\<computed> \[as calledWith\] (tests/component.js:30476:17)  
         at Context.\<anonymous> (tests/component.js:51840:63)

   when "component.readOnly" changes to "false"  
     ✖ should call "instance.setReadOnly"  
       Chrome 87.0.4280.66 (Linux x86\_64)  
     AssertError: expected setReadOnly to be called with arguments   
         at Object.fail (tests/component.js:30493:25)  
         at failAssertion (tests/component.js:30450:20)  
         at Object.assert.\<computed> \[as calledWith\] (tests/component.js:30476:17)  
         at Context.\<anonymous> (tests/component.js:51840:63)  
\`\`\`

**Comment by sculpt0r** [comment]
Rebase onto newest `master`.

**Comment by sculpt0r** [comment]
After rebase, all local tests are green :)

**Comment by sculpt0r** [comment]
Summary:

*   add BrowserStack IE11 launcher
*   failing syntax on IE11 (also failing tests) - fixed with ckeditor/ckeditor4-integrations-common#15. Now common integration distributes properly transpiled code
*   still failing tests on IE11 fixed with 2f31df4:
    *   `Object.entries` was in usage, but IE doesn't support it
    *   Cannot use `CKEDITOR.tools` for `Object.entries` or `reduce`, because we are testing CKEditor namespace loading. There is cached Namespace before we delete `window.CKEditor`, but inner code of tools stills relay on global CKEditor variable, so it's hard to usage
    *   Simplified object iteration: actually we are passing only simple object constructs (`{ prop:value}`) to fill element props. So there is no need to validate all specific cases like our `tools` are handling it.

Waiting for CI forever...  
Finally, it's ready for review.

**Review by Dumluregn — CHANGES_REQUESTED** [review]
Looks good 👍🏻 Only one small thing left - in [test code coverage](https://travis-ci.org/github/ckeditor/ckeditor4-vue/builds/756382199) I see that for one browser (I guess it's IE11 but I'm not sure) there is one line uncovered: `108`. Could you examine if that's expected or the tests can be improved to check also this condition?

**Comment by sculpt0r** [comment]
Indeed - It's IE11...

**Review by Dumluregn — APPROVED** [review]
Thanks for checking the coverage thing. I've checked and the flag is still necessary in IE11, so as you wrote we have to leave it. Other than that - 👍🏻

**Comment by Dumluregn** [comment]
CI is green, so I'm merging the PR 👍🏻

**Pull request merged**
